export {
  createPostgresRouteSelectionOwner,
  snapshotRouteSelectionCurrent,
  type PostgresRouteSelectionOwner,
  type RouteSelectionInput,
  type RouteSelectionCurrent,
  createDispatchConsumptionRequestDigests,
  createCredentialMaterializationRequestDigest,
  createInMemoryContainedTurnDispatchConsumptionV1,
  createStaticContainedTurnProviderAccessFeature,
  type InMemoryDispatchBindingSeed,
  type InMemoryDispatchConsumptionHarness,
  type StaticAvailableProviderAccessAuthority,
  type StaticIndeterminateProviderAccessAuthority,
  type StaticProviderAccessAuthority,
} from "./features/contained-turn-access/internal.js";
export { createPostgresDispatchConsumption, type DispatchHeadPublication, type DispatchHeadPublicationResult,
  type DispatchPostgresControl, type DispatchPostgresOwner, type PostgresDispatchConsumptionObservation,
  type PostgresDispatchConsumptionOwner } from "./features/contained-turn-access/internal.js";
export { createPostgresCredentialRenderingOwner, createPostgresMaterializationRepository,
  materializationPostgresSchemaDigest, routeSelectionSchemaDigest, dispatchOperationSchemaDigest,
  type MaterializationPostgresPool, type MaterializationPostgresTimeouts,
  type PostgresCredentialRenderingOwner, type PostgresMaterializationRepositoryOwner,
  type CredentialRenderingSelection, type CredentialGenerationAcquisition,
  type CredentialRenderingBinding, type OperationCredentialMaterialAdmission } from "./features/contained-turn-access/internal.js";
export { createPostgresOperationDispatchConsumption, createPostgresCurrentProviderAccess,
  type PaAcceptedPreparation, type PaDispatchIssuanceSelection,
  type PostgresCurrentProviderAccessOwner,
  type PostgresOperationDispatchConsumptionOwner } from "./features/contained-turn-access/internal.js";
export {
  createContainedTurnCredentialMaterializationAuthorizationV1,
  createContainedTurnCredentialRenderingOwner, createContainedTurnProviderAccessFeature,
  createInMemoryDispatchConsumptionRepository, createMaterializationBindingRepository,
  createOperationDispatchConsumption, createSha256DispatchConsumptionDigest, routeSelectionDigest,
  snapshotRouteSelectionFacts, type OperationDispatchConsumptionOwner,
} from "./features/contained-turn-access/internal.js";

export { createOrdinaryCodexAuthCapture, OrdinaryCodexAuthRefused, OrdinaryCodexAuthCleanupIndeterminate,
  type OrdinaryCodexAuthCapture, type OrdinaryCodexAuthCaptureOptions, type OrdinaryCodexAuthMetadata,
  type OrdinaryCodexAuthObservation } from './features/contained-turn-access/internal.js';

export { createPostgresOrdinaryProviderAccessOwner, type OrdinaryProviderAccessOwnerOptions } from './features/contained-turn-access/internal.js';
export { OrdinaryPaUnavailable, type OrdinaryPaBinding, type OrdinaryPaAuthority, type OrdinaryPaSnapshot,
  type OrdinaryPaMaterial, type OrdinaryPaRetirement, type OrdinaryPaSettlement, type OrdinaryPaGrant } from './features/contained-turn-access/internal.js';

/** Type-only closure of the trusted Provider Access composition factories. */
export type {
  AuthorizationCommand,
  AuthorizationProvider,
  AuthorizationRecord,
  AuthorizationRejectionReason,
  AuthorizeCredentialMaterializationInput,
  AuthorizeCredentialMaterializationOutcome,
  ContainedTurnDispatchConsumptionV1,
  ContainedTurnProviderAccessBinding,
  ContainedTurnProviderAccessBindingObservation,
  ContainedTurnProviderAccessBindingSnapshot,
  ContainedTurnProviderAccessDependencies,
  ContainedTurnProviderAccessFeatureApi,
  ContainedTurnProviderAccessRepository,
  ConsumeForDispatchInput,
  ConsumeForDispatchOutcome,
  CredentialGenerationField,
  CredentialGenerationOutcome,
  CredentialGenerationRequest,
  CredentialMaterializationAuthorizationReceipt,
  CredentialMaterializationAuthorizationV1,
  CredentialMaterializationRejectionReason,
  CredentialMaterializationUnsupportedReason,
  CredentialRecipe,
  CredentialRenderingOutcome,
  CredentialRenderingOwner,
  DispatchBindingHead,
  DispatchConsumeOutcome,
  DispatchConsumedReceipt,
  DispatchConsumptionBindingExpectation,
  DispatchConsumptionDigest,
  DispatchConsumptionDisposition,
  DispatchConsumptionJournalEntry,
  DispatchConsumptionOwnerState,
  DispatchConsumptionPrevention,
  DispatchConsumptionPreventedReason,
  DispatchConsumptionReceipt,
  DispatchConsumptionRepository,
  DispatchConsumptionScope,
  DispatchConsumptionSettlementReceipt,
  DispatchConsumptionTransaction,
  DispatchConsumptionTransactionSelector,
  DispatchDisposition,
  DispatchExpectationValue,
  DispatchPrevention,
  DispatchPreventedReason,
  DispatchProvider,
  DispatchScopeValue,
  DispatchSettlementOutcome,
  DispatchSettlementReceipt,
  InMemoryDispatchConsumptionControl,
  MaterializationAuthorizationBinding,
  MaterializationAuthorizationDigest,
  MaterializationAuthorizationRepository,
  MaterializationAuthorizationRequestSelector,
  MaterializationAuthorizationTransaction,
  MaterializationAuthorizationV1Dependencies,
  MaterializationPostgresClient,
  MaterializationPostgresOwner,
  ObserveCredentialMaterializationAuthorizationInput,
  ObserveCredentialMaterializationAuthorizationOutcome,
  ObserveDispatchConsumptionInput,
  ObserveDispatchConsumptionOutcome,
  OrdinaryCodexAuthReason,
  OrdinaryCodexAuthStage,
  PaOperationOwner,
  PaOperationRecordKind,
  PaOperationStore,
  PaOperationTransaction,
  ProviderAccessAuthorityEvidence,
  ProviderAccessProvider,
  ProviderAccessScope,
  ProviderAccessUnavailableReason,
  RenderedCredentialField,
  RenderedCredentialFields,
  RevalidateContainedTurnProviderAccess,
  RevalidateContainedTurnProviderAccessInput,
  RevalidateContainedTurnProviderAccessOutcome,
  RevalidateContainedTurnProviderAccessRejection,
  ResolveContainedTurnProviderAccess,
  ResolveContainedTurnProviderAccessInput,
  ResolveContainedTurnProviderAccessOutcome,
  RouteSelectionDescriptor,
  RouteSelectionFacts,
  SettleDispatchConsumptionInput,
  SettleDispatchConsumptionOutcome,
  TrustedCredentialMaterialSeed,
} from "./features/contained-turn-access/internal.js";
